### ISSUE TITLE
Igea experiment

### ISSUE THREAD

**Issue by hovey** [autotwin/mesh#17]
Reproduce the 

* sphere experiment https://github.com/autotwin/mesh/blob/main/doc/sphere_mesh_refinement.md
* Stanford bunny experiment https://github.com/autotwin/mesh/blob/main/doc/bunny_mesh_refinement.md

Apply this to create a new experimental and write up (markdown, with a pull request when completed), for Igea.

**Comment by hovey** [comment]
You may want to upgrade your fork to version `0.0.7` and use the new "entry points" to save you some typing.

**Comment by calehma** [comment]
Will do. I actually spent yesterday updating my Mac to work with the proxies, so it looks like we now have both a Windows and Mac test environment to work in.

**Comment by hovey** [comment]
Wonderful!

**Comment by hovey** [comment]
@calehma Do you want to have a discussion to this week to review this item?

**Comment by calehma** [comment]
@hovey Yes, that's probably a good idea. I should be around all this week after 9a MT and outside of 12-2p MT Tuesday and Friday. I have the data from Igea and an updated markdown file. There was a question I had about how to get the volume metric, but I can take a swing at that later this week.

**Comment by hovey** [comment]
Completed.  See https://github.com/autotwin/mesh/blob/main/doc/igea_mesh_refinement.md
