### ISSUE TITLE
Python functions to wrap Cubit mesh metrics

### ISSUE THREAD

**Issue by hovey** [autotwin/mesh#25]
Currently, we have the minimum scaled Jacobian (MSJ) from Cubit accessible through Python

* see [`cubit_inp_to_minsj_csv.py`](https://github.com/autotwin/mesh/blob/main/src/atmesh/cubit_inp_to_minsj_csv.py)

We need the following (two, and possibly four) scripts to be created:

* `cubit_inp_to_skew_csv.py` page 97 of 107 of [2],
* `cubit_inp_to_aspect_ratio_csv.py` (aka *Maximum edge ratio*) page 87 of 107 of [2]
* ~~`cubit_inp_to_warp_csv.py`~~  # This seems like a quadrilateral metric, not a hexahedral metric.
* ~~`cubit_inp_to_min_max_angle_csv.py`~~  # This seems like a quadrilateral metric, not a hexahedral metric.

Reference:

* [1] [Li 2022](https://www.biorxiv.org/content/10.1101/2021.04.10.439281v1) Table 2 (page 14) uses these same metrics, and we may wish to benchmark our results with their results.
* [2] Stimpson C, Ernst C, Knupp P, Pébay P, Thompson D. The verdict library reference manual. Sandia National Laboratories Technical Report. 2007 May 8;9(6), [pdf](https://itk.org/Wiki/images/6/6b/VerdictManual-revA.pdf)
  * Cubit makes use of the [Verdict](https://github.com/sandialabs/verdict) library for mesh quality metrics.  
  * There is also a [Kitware version](https://gitlab.kitware.com/verdict/verdict).
* [3] The [quad_quality.pdf](https://github.com/sandialabs/sibl/blob/master/geo/doc/mesh/quad_quality.pdf) document may also be useful.

**Comment by calehma** [comment]
Skew script completed. Will update repository with aspect ratio next.

**Comment by calehma** [comment]
Completed the second of the hexahedral quality metric scripts. Do you want to go ahead with the quadrahedral metric scripts as well?

**Comment by hovey** [comment]
I have ~~crossed-out~~ the two quad-related metrics.  We currently have no plan to use quads in our meshes.  The Li 2022 meshes used both hex elements and quad elements, which explains why warp and min/max angle were also included in their work.  

So, please cancel the request for the quad-related items.  I will mark this issue as completed.
