### ISSUE TITLE
Test broadcast of GitHub Team called "all-members"

### ISSUE THREAD

**Issue by hovey** [autotwin/mesh#31]
2023-05-09-1144-MST

# Test of broadcast of GitHub Team called "all-members"

Chad created an "Issue" on the autotwin/mesh repo, then mentioned the "all-members" team with the "@" symbol as
autotwin/all-members (typed as @autotwin/all-members ).

Hopefully all Autotwin repo members receive a copy of this broadcast.

Please reply to this item if you receive it. Thank you.

Chad

**Comment by calehma** [comment]
Hi Chad,

Got it.

-Connor

From: Chad B. Hovey ***@***.***>
Sent: Tuesday, May 9, 2023 1:47 PM
To: autotwin/mesh ***@***.***>
Cc: Lehman, Connor Alexander ***@***.***>; Team mention ***@***.***>
Subject: [EXTERNAL] [autotwin/mesh] Test broadcast of GitHub Team called "all-members" (Issue #31)


2023-05-09-1144-MST

Test of broadcast of GitHub Team called "all-members"

Chad created an "Issue" on the autotwin/mesh repo, then mentioned the "all-members" team with the "@" symbol as
autotwin/all-members (typed as @autotwin/all-members<https://github.com/orgs/autotwin/teams/all-members> ).

Hopefully all Autotwin repo members receive a copy of this broadcast.

Please reply to this item if you receive it. Thank you.

Chad

-

**Comment by quan-bu** [comment]
Hi Chad,

I've received the message.

Best,
Quan

**Comment by saeedmhz** [comment]
Hi Chad,

I got the message.

Best,
Saeed

**Comment by CompMechPitt** [comment]
Hi Chad, 

Received your message. 
Have a great day ahead!

Best,
Manik

**Comment by HibaKob** [comment]
Received.

Best,
Hiba

**Comment by lingxiaoyuan** [comment]
Hi Chad,

I received the message.

Best,
Lingxiao
