### ISSUE TITLE
CL assistance

### ISSUE THREAD

**Issue by hovey** [autotwin/mesh#7]
10 hr/week, target 15-20 hr/ week max.

**Comment by hovey** [comment]
- [ ] Install Cubit version 16.06.
- [ ] Install Python 3.7.x where x can be any minor version.
- [ ] Start a `notes.txt` document that records the full install path for Cubit and full install path for Python.
- [ ] Review `2022-08-23-Getting-Started.pdf` file.

**Comment by calehma** [comment]
> * [ ]  Install Cubit version 16.06.
> * [ ]  Install Python 3.7.x where x can be any minor version.
> * [ ]  Start a `notes.txt` document that records the full install path for Cubit and full install path for Python.
> * [ ]  Review `2022-08-23-Getting-Started.pdf` file.
> * [ ]  Create a GitHub account (if you don't already have one, as you will need to do pull requests for this autotwin/mesh repo).
> 
> Next:
> 
> * [ ]  Local: `cd ~/autotwin/`
> * [ ]  fork this repo `https://github.com/autotwin/mesh`
> * [ ]  then `git clone` your forked version into the `~/autotwin/` folder
> * [ ]  create a virtual environment `atmeshenv` following these instructions `https://github.com/autotwin/mesh/blob/main/config/README.md`
> * [ ]  verify `.quality` and `.style` shell scripts run to completion

Quoting to track the status

**Comment by calehma** [comment]
Tasks are completed as of 8/24/22 9:50a MT

**Comment by hovey** [comment]
In the `mesh/examples` folder, can you please construct a "stand-alone" (can run from the command line) script called `examplar_boxplot.py` that makes six exemplar [matplotlib box plots](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.boxplot.html).   The result of the script will output a `.png` that appears similar to this:
<img width="500" alt="Screen Shot 2022-08-24 at 10 17 13" src="https://user-images.githubusercontent.com/1473854/186470206-83b61a2b-43c7-45e2-a094-034df556aa56.png">

You can hard code six different distributions between zero and one using numpy.   This effort will be a template for how we do a study later.

The study later will investigate minimum scaled Jacobian distributions as a function of study number.  Each successive study will try to make the distribution push closer toward unity (away from zero), and have a tighter band on the spread of the distribution.

It doesn't matter so much what the exemplar hard code distributions are, as long as you can
* have a minimum value > 0
* have a maximum value < 1
* assess the 25%ile, 50%ile, and 75%ile
* draw a box plot indicating the quartiles as shown above.

**Comment by calehma** [comment]
Update has been pushed. I ordered the boxes based on increasing median values, so the xlabel case numbers appear wonky. I can change that back, if needed.

**Comment by hovey** [comment]
Having the xlabel order as you have it is just fine.  The critical step here you achieved, which was to make a small example of a box plot, so we can use it in the larger algorithms later.

**Comment by hovey** [comment]
I am guessing you already know markdown, but just in case, this guide may be helpful: This markdown guide may be helpful to you: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by calehma** [comment]
> Having the xlabel order as you have it is just fine. The critical step here you achieved, which was to make a small example of a box plot, so we can use it in the larger algorithms later.

The meeting yesterday helped clear up questions I had regarding this. If your hypothesis is correct, then the xlabel should be in ascending order, assuming we label the box plots along the x-axis using something like cell count (or cell count/volume, I'm not entirely sure the metric used is since FEA is outside my wheelhouse). It might be a little bit extra, but it could be a useful tool to double-check the data.

**Comment by hovey** [comment]
fyi, i am updating sensitivity.py so it loops over _n_ input files.  more to come later...

**Comment by hovey** [comment]
Can you please try to tackle this one next?  I think it is in your wheelhouse.

- [ ] study the diff I made to your original `exemplar_boxplot.py` file here: https://github.com/autotwin/mesh/commit/57438156d14acd7fa07a4418e614be0b6231953e#diff-f0e7ce47bf5f87bbee9acad6d7e27dbeaa5d51f641d4a493ba9e98942c2965da

```python
n_studies = 6  # define once-and-for-all, avoid magic numbers later
```

Just a minor style point that allows code to become D.R.Y. (don't repeat yourself), and allow the code to be *array-reflective* --- that is if the array size changes, all other downstream code automatically changes (no need to update magic numbers appearing downstream in the code).

**Comment by hovey** [comment]
Next, and can you tackle this one:

- [ ] Review https://github.com/autotwin/mesh/blob/main/examples/sensitivity.py#L33 and https://github.com/autotwin/mesh/blob/main/examples/sensitivity.py#L171
- [ ] Can you use your `exemplar_boxplot.py` source as inspiration to extend `sensitivity.py` so that the _n_ histograms are plotted at the end of the script?

**Comment by calehma** [comment]
> Next, and can you tackle this one:
> 
> * [ ]  Review https://github.com/autotwin/mesh/blob/main/examples/sensitivity.py#L33 and https://github.com/autotwin/mesh/blob/main/examples/sensitivity.py#L171
> * [ ]  Can you use your `exemplar_boxplot.py` source as inspiration to extend `sensitivity.py` so that the _n_ histograms are plotted at the end of the script?

Quoting so I can check off the box as I go.

**Comment by hovey** [comment]
To let you know, it looks like I got `bounding_box` and `cell` intervals implemented in `.yml` input file, so soon we can launch another automated study.  So, more work coming in the pipe!   FYI.

**Comment by calehma** [comment]
Just wanted to bump the thread. I submitted a merge request from my fork a couple weeks back. Is there anything else you want me working on at the moment?

**Comment by hovey** [comment]
Thanks for the PR.   I am at a conference this week and will try to get the PR merged.  No other near-term actions until I after a bit the merge.  Thanks also for bumping the thread, email alerted me to the same.  Cheers.

**Comment by hovey** [comment]
Started to refactor this weekend.  Do you mind sending me a Teams invite on my calendar for a day/time that suits you this coming work week (if at all, since you might be too busy, which is fine too).

**Comment by hovey** [comment]
I moved most of the IO user configuration into `.yml` files (see https://github.com/autotwin/mesh/blob/main/doc/sphere_mesh_refinement.md#create-inp-files) and have flattened and separated out the concerns from the `sensitivity.py` script.  So now there are independent scripts that do file IO as follows:

* `.stl` to `.inp`
* `.inp` to minimum scaled Jacobian `.csv`

Next, the individual `.csv` files can be used with the histogram plotting, and I will take that up next week.   This too can use a `.yml` input file to control things like plot color, line width, etc.  

The benefit of the `.yml` approach is that we separate configuration from methodology.  Then, one methodology can operate on $n$ number of configuration states.  Also, then our methods do not have hard-coding to configuration.

This note is just FYI to explain some of the rationale behind the updates.
